FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy app files
COPY . .

# Build the application
RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

# Start the application
CMD ["npm", "run", "start"]
