"""Add vehicle_types table

Revision ID: 50897775e9cd
Revises: eb3cbeb06f84
Create Date: 2026-01-27 08:51:23.939953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50897775e9cd'
down_revision = 'eb3cbeb06f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hebrew', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_types_id'), 'vehicle_types', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_types_org_id'), 'vehicle_types', ['org_id'], unique=False)
    op.drop_table('schema_versions')
    op.drop_index('idx_audit_logs_org_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.drop_constraint('audit_logs_org_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_customers_org_id', table_name='customers')
    op.create_index(op.f('ix_customers_org_id'), 'customers', ['org_id'], unique=False)
    op.drop_constraint('customers_org_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_delivery_notes_org_id', table_name='delivery_notes')
    op.create_index(op.f('ix_delivery_notes_org_id'), 'delivery_notes', ['org_id'], unique=False)
    op.drop_constraint('fk_delivery_notes_org', 'delivery_notes', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_notes', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_drivers_org_id', table_name='drivers')
    op.drop_index('idx_drivers_truck', table_name='drivers')
    op.create_index(op.f('ix_drivers_org_id'), 'drivers', ['org_id'], unique=False)
    op.drop_constraint('drivers_default_truck_id_fkey', 'drivers', type_='foreignkey')
    op.drop_constraint('drivers_org_id_fkey', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'organizations', ['org_id'], ['id'])
    op.drop_column('drivers', 'default_truck_id')
    op.drop_index('idx_expenses_org_id', table_name='expenses')
    op.create_index(op.f('ix_expenses_org_id'), 'expenses', ['org_id'], unique=False)
    op.drop_constraint('expenses_org_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_files_org_id', table_name='files')
    op.create_index(op.f('ix_files_org_id'), 'files', ['org_id'], unique=False)
    op.drop_constraint('files_org_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_job_status_events_org_id', table_name='job_status_events')
    op.create_index(op.f('ix_job_status_events_org_id'), 'job_status_events', ['org_id'], unique=False)
    op.drop_constraint('fk_job_status_events_org', 'job_status_events', type_='foreignkey')
    op.create_foreign_key(None, 'job_status_events', 'organizations', ['org_id'], ['id'])
    op.alter_column('jobs', 'is_subcontractor',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='האם הנסיעה בוצעה ע"י קבלן משנה',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('jobs', 'subcontractor_price_breakdown_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='פירוט חישוב מחיר לקבלן',
               existing_nullable=True)
    op.drop_index('idx_jobs_is_subcontractor', table_name='jobs')
    op.drop_index('idx_jobs_org_id', table_name='jobs')
    op.drop_index('idx_jobs_subcontractor', table_name='jobs')
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.drop_constraint('jobs_subcontractor_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_org_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'subcontractors', ['subcontractor_id'], ['id'])
    op.drop_index('idx_materials_org_id', table_name='materials')
    op.create_index(op.f('ix_materials_org_id'), 'materials', ['org_id'], unique=False)
    op.drop_constraint('materials_org_id_fkey', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_organizations_contact_email', table_name='organizations')
    op.drop_index('idx_organizations_plan_type', table_name='organizations')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_index('idx_organizations_status', table_name='organizations')
    op.drop_constraint('organizations_contact_email_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_contact_email'), 'organizations', ['contact_email'], unique=True)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.drop_index('idx_payment_allocations_org_id', table_name='payment_allocations')
    op.create_index(op.f('ix_payment_allocations_org_id'), 'payment_allocations', ['org_id'], unique=False)
    op.drop_constraint('fk_payment_allocations_org', 'payment_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'payment_allocations', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_payments_org_id', table_name='payments')
    op.create_index(op.f('ix_payments_org_id'), 'payments', ['org_id'], unique=False)
    op.drop_constraint('payments_org_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_price_lists_org_id', table_name='price_lists')
    op.create_index(op.f('ix_price_lists_org_id'), 'price_lists', ['org_id'], unique=False)
    op.drop_constraint('price_lists_org_id_fkey', 'price_lists', type_='foreignkey')
    op.create_foreign_key(None, 'price_lists', 'organizations', ['org_id'], ['id'])
    op.alter_column('share_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_share_urls_job_id', table_name='share_urls')
    op.drop_index('idx_share_urls_org_id', table_name='share_urls')
    op.drop_constraint('share_urls_short_id_key', 'share_urls', type_='unique')
    op.create_index(op.f('ix_share_urls_id'), 'share_urls', ['id'], unique=False)
    op.create_index(op.f('ix_share_urls_org_id'), 'share_urls', ['org_id'], unique=False)
    op.create_index(op.f('ix_share_urls_short_id'), 'share_urls', ['short_id'], unique=True)
    op.drop_constraint('share_urls_created_by_fkey', 'share_urls', type_='foreignkey')
    op.drop_constraint('share_urls_org_id_fkey', 'share_urls', type_='foreignkey')
    op.drop_constraint('share_urls_job_id_fkey', 'share_urls', type_='foreignkey')
    op.create_foreign_key(None, 'share_urls', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'share_urls', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'share_urls', 'organizations', ['org_id'], ['id'])
    op.alter_column('sites', 'is_generic',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='אתר כללי (מחצבה, תחנת דלק) - לא משויך ללקוח ספציפי',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_sites_generic', table_name='sites')
    op.drop_index('idx_sites_org_id', table_name='sites')
    op.create_index(op.f('ix_sites_org_id'), 'sites', ['org_id'], unique=False)
    op.drop_constraint('sites_org_id_fkey', 'sites', type_='foreignkey')
    op.create_foreign_key(None, 'sites', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_statement_lines_org_id', table_name='statement_lines')
    op.create_index(op.f('ix_statement_lines_org_id'), 'statement_lines', ['org_id'], unique=False)
    op.drop_constraint('fk_statement_lines_org', 'statement_lines', type_='foreignkey')
    op.create_foreign_key(None, 'statement_lines', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_statements_org_id', table_name='statements')
    op.create_index(op.f('ix_statements_org_id'), 'statements', ['org_id'], unique=False)
    op.drop_constraint('statements_org_id_fkey', 'statements', type_='foreignkey')
    op.create_foreign_key(None, 'statements', 'organizations', ['org_id'], ['id'])
    op.alter_column('subcontractor_price_lists', 'valid_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subcontractor_price_lists', 'valid_to',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subcontractor_price_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subcontractor_price_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_subcontractor_prices_customer', table_name='subcontractor_price_lists')
    op.drop_index('idx_subcontractor_prices_org', table_name='subcontractor_price_lists')
    op.drop_index('idx_subcontractor_prices_sub', table_name='subcontractor_price_lists')
    op.drop_index('idx_subcontractor_prices_truck', table_name='subcontractor_price_lists')
    op.create_index(op.f('ix_subcontractor_price_lists_id'), 'subcontractor_price_lists', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractor_price_lists_org_id'), 'subcontractor_price_lists', ['org_id'], unique=False)
    op.drop_constraint('subcontractor_price_lists_from_site_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_org_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_truck_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_to_site_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_subcontractor_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_material_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint('subcontractor_price_lists_customer_id_fkey', 'subcontractor_price_lists', type_='foreignkey')
    op.create_foreign_key(None, 'subcontractor_price_lists', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'trucks', ['truck_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'subcontractors', ['subcontractor_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'sites', ['from_site_id'], ['id'])
    op.create_foreign_key(None, 'subcontractor_price_lists', 'sites', ['to_site_id'], ['id'])
    op.drop_table_comment(
        'subcontractor_price_lists',
        existing_comment='מחירונים לקבלני משנה',
        schema=None
    )
    op.alter_column('subcontractors', 'payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='weekly/monthly/per_trip',
               existing_nullable=True,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.alter_column('subcontractors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subcontractors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_subcontractors_active', table_name='subcontractors')
    op.drop_index('idx_subcontractors_org', table_name='subcontractors')
    op.create_index(op.f('ix_subcontractors_id'), 'subcontractors', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractors_org_id'), 'subcontractors', ['org_id'], unique=False)
    op.drop_constraint('subcontractors_org_id_fkey', 'subcontractors', type_='foreignkey')
    op.create_foreign_key(None, 'subcontractors', 'organizations', ['org_id'], ['id'])
    op.drop_table_comment(
        'subcontractors',
        existing_comment='קבלני משנה - ספקי שירותי הובלה חיצוניים',
        schema=None
    )
    op.drop_index('idx_trailers_org_id', table_name='trailers')
    op.create_index(op.f('ix_trailers_org_id'), 'trailers', ['org_id'], unique=False)
    op.drop_constraint('trailers_org_id_fkey', 'trailers', type_='foreignkey')
    op.create_foreign_key(None, 'trailers', 'organizations', ['org_id'], ['id'])
    op.alter_column('trucks', 'owner_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='COMPANY or SUBCONTRACTOR',
               existing_nullable=True,
               existing_server_default=sa.text("'COMPANY'::character varying"))
    op.alter_column('trucks', 'subcontractor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='אם owner_type=SUBCONTRACTOR, מכיל FK לקבלן',
               existing_nullable=True)
    op.drop_index('idx_trucks_org_id', table_name='trucks')
    op.drop_index('idx_trucks_owner', table_name='trucks')
    op.drop_index('idx_trucks_subcontractor', table_name='trucks')
    op.create_index(op.f('ix_trucks_org_id'), 'trucks', ['org_id'], unique=False)
    op.drop_constraint('trucks_subcontractor_id_fkey', 'trucks', type_='foreignkey')
    op.drop_constraint('trucks_org_id_fkey', 'trucks', type_='foreignkey')
    op.create_foreign_key(None, 'trucks', 'subcontractors', ['subcontractor_id'], ['id'])
    op.create_foreign_key(None, 'trucks', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_user_roles_org_id', table_name='user_roles')
    op.create_index(op.f('ix_user_roles_org_id'), 'user_roles', ['org_id'], unique=False)
    op.drop_constraint('user_roles_org_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_users_org_id', table_name='users')
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.drop_constraint('users_org_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    op.drop_index('idx_weigh_tickets_org_id', table_name='weigh_tickets')
    op.create_index(op.f('ix_weigh_tickets_org_id'), 'weigh_tickets', ['org_id'], unique=False)
    op.drop_constraint('fk_weigh_tickets_org', 'weigh_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'weigh_tickets', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weigh_tickets', type_='foreignkey')
    op.create_foreign_key('fk_weigh_tickets_org', 'weigh_tickets', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_weigh_tickets_org_id'), table_name='weigh_tickets')
    op.create_index('idx_weigh_tickets_org_id', 'weigh_tickets', ['org_id'], unique=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_org_id_fkey', 'users', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_org_id_fkey', 'user_roles', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_roles_org_id'), table_name='user_roles')
    op.create_index('idx_user_roles_org_id', 'user_roles', ['org_id'], unique=False)
    op.drop_constraint(None, 'trucks', type_='foreignkey')
    op.drop_constraint(None, 'trucks', type_='foreignkey')
    op.create_foreign_key('trucks_org_id_fkey', 'trucks', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trucks_subcontractor_id_fkey', 'trucks', 'subcontractors', ['subcontractor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_trucks_org_id'), table_name='trucks')
    op.create_index('idx_trucks_subcontractor', 'trucks', ['subcontractor_id'], unique=False)
    op.create_index('idx_trucks_owner', 'trucks', ['org_id', 'owner_type'], unique=False)
    op.create_index('idx_trucks_org_id', 'trucks', ['org_id'], unique=False)
    op.alter_column('trucks', 'subcontractor_id',
               existing_type=sa.INTEGER(),
               comment='אם owner_type=SUBCONTRACTOR, מכיל FK לקבלן',
               existing_nullable=True)
    op.alter_column('trucks', 'owner_type',
               existing_type=sa.VARCHAR(length=20),
               comment='COMPANY or SUBCONTRACTOR',
               existing_nullable=True,
               existing_server_default=sa.text("'COMPANY'::character varying"))
    op.drop_constraint(None, 'trailers', type_='foreignkey')
    op.create_foreign_key('trailers_org_id_fkey', 'trailers', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_trailers_org_id'), table_name='trailers')
    op.create_index('idx_trailers_org_id', 'trailers', ['org_id'], unique=False)
    op.create_table_comment(
        'subcontractors',
        'קבלני משנה - ספקי שירותי הובלה חיצוניים',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'subcontractors', type_='foreignkey')
    op.create_foreign_key('subcontractors_org_id_fkey', 'subcontractors', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subcontractors_org_id'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_id'), table_name='subcontractors')
    op.create_index('idx_subcontractors_org', 'subcontractors', ['org_id'], unique=False)
    op.create_index('idx_subcontractors_active', 'subcontractors', ['org_id', 'is_active'], unique=False)
    op.alter_column('subcontractors', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subcontractors', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subcontractors', 'payment_terms',
               existing_type=sa.VARCHAR(length=100),
               comment='weekly/monthly/per_trip',
               existing_nullable=True,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.create_table_comment(
        'subcontractor_price_lists',
        'מחירונים לקבלני משנה',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.drop_constraint(None, 'subcontractor_price_lists', type_='foreignkey')
    op.create_foreign_key('subcontractor_price_lists_customer_id_fkey', 'subcontractor_price_lists', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('subcontractor_price_lists_material_id_fkey', 'subcontractor_price_lists', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('subcontractor_price_lists_subcontractor_id_fkey', 'subcontractor_price_lists', 'subcontractors', ['subcontractor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcontractor_price_lists_to_site_id_fkey', 'subcontractor_price_lists', 'sites', ['to_site_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('subcontractor_price_lists_truck_id_fkey', 'subcontractor_price_lists', 'trucks', ['truck_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('subcontractor_price_lists_org_id_fkey', 'subcontractor_price_lists', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subcontractor_price_lists_from_site_id_fkey', 'subcontractor_price_lists', 'sites', ['from_site_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_subcontractor_price_lists_org_id'), table_name='subcontractor_price_lists')
    op.drop_index(op.f('ix_subcontractor_price_lists_id'), table_name='subcontractor_price_lists')
    op.create_index('idx_subcontractor_prices_truck', 'subcontractor_price_lists', ['truck_id'], unique=False)
    op.create_index('idx_subcontractor_prices_sub', 'subcontractor_price_lists', ['subcontractor_id'], unique=False)
    op.create_index('idx_subcontractor_prices_org', 'subcontractor_price_lists', ['org_id'], unique=False)
    op.create_index('idx_subcontractor_prices_customer', 'subcontractor_price_lists', ['customer_id'], unique=False)
    op.alter_column('subcontractor_price_lists', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('subcontractor_price_lists', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subcontractor_price_lists', 'valid_to',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('subcontractor_price_lists', 'valid_from',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.create_foreign_key('statements_org_id_fkey', 'statements', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_statements_org_id'), table_name='statements')
    op.create_index('idx_statements_org_id', 'statements', ['org_id'], unique=False)
    op.drop_constraint(None, 'statement_lines', type_='foreignkey')
    op.create_foreign_key('fk_statement_lines_org', 'statement_lines', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_statement_lines_org_id'), table_name='statement_lines')
    op.create_index('idx_statement_lines_org_id', 'statement_lines', ['org_id'], unique=False)
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.create_foreign_key('sites_org_id_fkey', 'sites', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sites_org_id'), table_name='sites')
    op.create_index('idx_sites_org_id', 'sites', ['org_id'], unique=False)
    op.create_index('idx_sites_generic', 'sites', ['org_id', 'is_generic'], unique=False)
    op.alter_column('sites', 'is_generic',
               existing_type=sa.BOOLEAN(),
               comment='אתר כללי (מחצבה, תחנת דלק) - לא משויך ללקוח ספציפי',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'share_urls', type_='foreignkey')
    op.drop_constraint(None, 'share_urls', type_='foreignkey')
    op.drop_constraint(None, 'share_urls', type_='foreignkey')
    op.create_foreign_key('share_urls_job_id_fkey', 'share_urls', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('share_urls_org_id_fkey', 'share_urls', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('share_urls_created_by_fkey', 'share_urls', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_share_urls_short_id'), table_name='share_urls')
    op.drop_index(op.f('ix_share_urls_org_id'), table_name='share_urls')
    op.drop_index(op.f('ix_share_urls_id'), table_name='share_urls')
    op.create_unique_constraint('share_urls_short_id_key', 'share_urls', ['short_id'])
    op.create_index('idx_share_urls_org_id', 'share_urls', ['org_id'], unique=False)
    op.create_index('idx_share_urls_job_id', 'share_urls', ['job_id'], unique=False)
    op.alter_column('share_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'price_lists', type_='foreignkey')
    op.create_foreign_key('price_lists_org_id_fkey', 'price_lists', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_price_lists_org_id'), table_name='price_lists')
    op.create_index('idx_price_lists_org_id', 'price_lists', ['org_id'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_org_id_fkey', 'payments', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_org_id'), table_name='payments')
    op.create_index('idx_payments_org_id', 'payments', ['org_id'], unique=False)
    op.drop_constraint(None, 'payment_allocations', type_='foreignkey')
    op.create_foreign_key('fk_payment_allocations_org', 'payment_allocations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payment_allocations_org_id'), table_name='payment_allocations')
    op.create_index('idx_payment_allocations_org_id', 'payment_allocations', ['org_id'], unique=False)
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_contact_email'), table_name='organizations')
    op.create_unique_constraint('organizations_contact_email_key', 'organizations', ['contact_email'])
    op.create_index('idx_organizations_status', 'organizations', ['status'], unique=False)
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_index('idx_organizations_plan_type', 'organizations', ['plan_type'], unique=False)
    op.create_index('idx_organizations_contact_email', 'organizations', ['contact_email'], unique=False)
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key('materials_org_id_fkey', 'materials', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_materials_org_id'), table_name='materials')
    op.create_index('idx_materials_org_id', 'materials', ['org_id'], unique=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_org_id_fkey', 'jobs', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jobs_subcontractor_id_fkey', 'jobs', 'subcontractors', ['subcontractor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.create_index('idx_jobs_subcontractor', 'jobs', ['subcontractor_id'], unique=False)
    op.create_index('idx_jobs_org_id', 'jobs', ['org_id'], unique=False)
    op.create_index('idx_jobs_is_subcontractor', 'jobs', ['org_id', 'is_subcontractor'], unique=False)
    op.alter_column('jobs', 'subcontractor_price_breakdown_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='פירוט חישוב מחיר לקבלן',
               existing_nullable=True)
    op.alter_column('jobs', 'is_subcontractor',
               existing_type=sa.BOOLEAN(),
               comment='האם הנסיעה בוצעה ע"י קבלן משנה',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'job_status_events', type_='foreignkey')
    op.create_foreign_key('fk_job_status_events_org', 'job_status_events', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_status_events_org_id'), table_name='job_status_events')
    op.create_index('idx_job_status_events_org_id', 'job_status_events', ['org_id'], unique=False)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_org_id_fkey', 'files', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_files_org_id'), table_name='files')
    op.create_index('idx_files_org_id', 'files', ['org_id'], unique=False)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_org_id_fkey', 'expenses', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expenses_org_id'), table_name='expenses')
    op.create_index('idx_expenses_org_id', 'expenses', ['org_id'], unique=False)
    op.add_column('drivers', sa.Column('default_truck_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='משאית ברירת מחדל לנהג'))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key('drivers_org_id_fkey', 'drivers', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('drivers_default_truck_id_fkey', 'drivers', 'trucks', ['default_truck_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_drivers_org_id'), table_name='drivers')
    op.create_index('idx_drivers_truck', 'drivers', ['default_truck_id'], unique=False)
    op.create_index('idx_drivers_org_id', 'drivers', ['org_id'], unique=False)
    op.drop_constraint(None, 'delivery_notes', type_='foreignkey')
    op.create_foreign_key('fk_delivery_notes_org', 'delivery_notes', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_delivery_notes_org_id'), table_name='delivery_notes')
    op.create_index('idx_delivery_notes_org_id', 'delivery_notes', ['org_id'], unique=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_org_id_fkey', 'customers', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customers_org_id'), table_name='customers')
    op.create_index('idx_customers_org_id', 'customers', ['org_id'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_org_id_fkey', 'audit_logs', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.create_index('idx_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_table('schema_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schema_versions_pkey'),
    sa.UniqueConstraint('version', name='schema_versions_version_key'),
    comment='מעקב אחר migrations שהופעלו במערכת'
    )
    op.drop_index(op.f('ix_vehicle_types_org_id'), table_name='vehicle_types')
    op.drop_index(op.f('ix_vehicle_types_id'), table_name='vehicle_types')
    op.drop_table('vehicle_types')
    # ### end Alembic commands ###
