"""add_user_permissions_and_phone_auth

Revision ID: 8638f613c082
Revises: add_alerts_002
Create Date: 2026-01-27 11:11:45.791673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8638f613c082'
down_revision = 'add_alerts_002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_expiry', table_name='alerts', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index('idx_alerts_org_user', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_type', table_name='alerts')
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.create_index('idx_alerts_type', 'alerts', ['alert_type', 'created_at'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity', 'status'], unique=False)
    op.create_index('idx_alerts_org_user', 'alerts', ['org_id', 'created_for_user_id', 'status'], unique=False)
    op.create_index('idx_alerts_expiry', 'alerts', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    # ### end Alembic commands ###
