"""add_trip_surcharge_to_price_lists

Revision ID: eb3cbeb06f84
Revises: 0de61025355d
Create Date: 2026-01-27 00:09:54.204933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb3cbeb06f84'
down_revision = '0de61025355d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_lists', sa.Column('trip_surcharge', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('sites', 'is_generic',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Generic site not tied to specific customer (quarry, fuel station, etc)',
               existing_nullable=True)
    op.drop_index('idx_sites_generic', table_name='sites', postgresql_where='(is_generic = true)')
    op.drop_index('idx_subcontractors_truck_plate', table_name='subcontractors')
    op.create_index(op.f('ix_subcontractors_truck_plate_number'), 'subcontractors', ['truck_plate_number'], unique=False)
    op.alter_column('trucks', 'primary_driver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary driver assigned to this truck',
               existing_nullable=True)
    op.alter_column('trucks', 'secondary_driver_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of secondary driver IDs assigned to this truck',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('idx_trucks_primary_driver', table_name='trucks')
    op.drop_index('idx_trucks_secondary_drivers', table_name='trucks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trucks_secondary_drivers', 'trucks', ['secondary_driver_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_trucks_primary_driver', 'trucks', ['primary_driver_id'], unique=False)
    op.alter_column('trucks', 'secondary_driver_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of secondary driver IDs assigned to this truck',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('trucks', 'primary_driver_id',
               existing_type=sa.INTEGER(),
               comment='Primary driver assigned to this truck',
               existing_nullable=True)
    op.drop_index(op.f('ix_subcontractors_truck_plate_number'), table_name='subcontractors')
    op.create_index('idx_subcontractors_truck_plate', 'subcontractors', ['truck_plate_number'], unique=False)
    op.create_index('idx_sites_generic', 'sites', ['is_generic'], unique=False, postgresql_where='(is_generic = true)')
    op.alter_column('sites', 'is_generic',
               existing_type=sa.BOOLEAN(),
               comment='Generic site not tied to specific customer (quarry, fuel station, etc)',
               existing_nullable=True)
    op.drop_column('price_lists', 'trip_surcharge')
    # ### end Alembic commands ###
